FROM openjdk:11
ENV	USE_PROFILE dev
ARG JAR_FILE=/build/libs/isb-portal-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} portal.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=${USE_PROFILE}", "-jar","/portal.jar"]

# 도커 빌드: docker build -f Dockerfile.dev -t isb-portal .
# 도커 실행: docker run --rm -p 22001:22001 --name isb-portal --network isb-portal-net isb-portal